desc "Download iOS terms as .xcstrings file"
lane :ios_xcstrings do
  ovo_poeditor_strings(
    api_token: "api_token",
    project_id: "project_id",
    languages: ["en", "fr", "it"],
    output_dir: "./XCStrings",
    file_format: "xcstrings",
    file_name: "Localizable.xcstrings"
  )
end

desc "Download iOS terms as .strings file"
lane :ios_strings do
  ovo_poeditor_strings(
    api_token: "api_token",
    project_id: "project_id",
    languages: ["en", "fr", "it"],
    output_dir: "./Strings",
    file_format: "apple_strings",
    file_name: "Localizable.strings"
  )
end

desc "Download Android terms as .xml file"
lane :android_strings do
  ovo_poeditor_strings(
    api_token: "api_token",
    project_id: "project_id",
    languages: ["en", "fr", "it"],
    output_dir: "./Android",
    file_format: "android_strings",
    file_name: "strings.xml"
  )
end